export const response = {
  form: {
    form_id: 128,
    after_email_sent_confirmation: '<p data-block-key="ht4j2">Thank you</p>',
    fields: [
      {
        touched: false,
        error: '',
        name: 'single_line_text',
        label: 'single_line_text',
        field_type: 'singleline',
        html_type: 'text',
        validation: [],
        required: true,
        value: '',
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'multiline_text',
        label: 'multiline_text',
        field_type: 'multiline',
        html_type: '',
        validation: [],
        required: true,
        value: '',
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'email',
        label: 'email',
        field_type: 'email',
        html_type: 'email',
        validation: ['email'],
        required: true,
        value: '',
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'number',
        label: 'number',
        field_type: 'number',
        html_type: 'text',
        validation: [],
        required: true,
        value: '',
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'url',
        label: 'url',
        field_type: 'url',
        html_type: '',
        validation: [],
        required: true,
        value: '',
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'my-checkbox',
        label: 'my checkbox',
        field_type: 'checkbox',
        html_type: '',
        validation: [],
        required: true,
        value: '',
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'checkboxes',
        label: 'checkboxes',
        field_type: 'checkboxes',
        html_type: '',
        options: ['a', 'b', 'c'],
        validation: [],
        required: true,
        value: [],
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'drop_down',
        label: 'drop_down',
        field_type: 'dropdown',
        html_type: '',
        options: ['', 'one', 'two', 'three'],
        validation: [],
        required: true,
        value: '',
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'radio_buttons',
        label: 'radio_buttons',
        field_type: 'radio',
        html_type: '',
        options: ['a', 'b', 'c'],
        validation: [],
        required: true,
        value: '',
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'date_time',
        label: 'date_time',
        field_type: 'datetime',
        html_type: '',
        validation: [],
        required: true,
        value: '',
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'unique',
        label: 'unique',
        field_type: 'uid',
        html_type: '',
        validation: [],
        required: true,
        value: '0lcolh98',
        help: '',
      },
      {
        touched: false,
        error: '',
        name: 'honey',
        label: 'Honey',
        field_type: 'wax',
        html_type: '',
        required: false,
        value: '',
        help: '',
      },
    ],
    csrf_token: 'yuEH9g36LH02QLhDCzgVEu5Q1bYNR1bERQhZqJvfo4mevDwZGGDS2ERIoRKYA1gm',
  },
}
